CREATE TABLE IF NOt EXISTS corporations (
    corporationId BIGINT PRIMARY KEY,
    name VARCHAR(255),
    icon256_url VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS TestOffersNPC (
    offer_id BIGINT PRIMARY KEY,
    type_id BIGINT,
    lp_cost BIGINT NOT NULL,
    isk_cost BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    corporation_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS offers_npc_corporation_required_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT PRIMARY KEY,
    type_order BOOLEAN NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    volume_remain BIGINT NOT NULL,
    system_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    item_id BIGINT
);

CREATE TABLE IF NOT EXISTS all_items (
    item_id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    discription VARCHAR(255),
    icon VARCHAR(512)
);